# Generated by Django 5.2.4 on 2025-07-16 19:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("car", "Car"),
                            ("truck", "Truck"),
                            ("bus", "Bus"),
                            ("van", "Van"),
                            ("suv", "SUV"),
                            ("motorcycle", "Motorcycle"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                (
                    "vin",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Chassis/VIN"
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("mileage", models.PositiveIntegerField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="inventory_images/"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold", "Sold"),
                            ("reserved", "Reserved"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventories",
                        to="accounts.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["-added_on"],
            },
        ),
    ]
