# Generated by Django 5.2.4 on 2025-08-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("account", "Account"),
                    ("procurement", "Procurement"),
                    ("workshop", "Workshop"),
                    ("sales", "Sales"),
                ],
                max_length=20,
            ),
        ),
    ]
