# Generated by Django 5.2.4 on 2025-07-09 10:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(default=accounts.models.generate_unique_id, editable=False, max_length=9, unique=True),
        ),
    ]
